# Generated by Django 3.0.4 on 2020-03-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categori',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='addres',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='addres',
            name='vender',
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Item'),
        ),
        migrations.AddField(
            model_name='bidder',
            name='addres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Addres'),
        ),
        migrations.AddField(
            model_name='categori',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vender',
            name='addres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Addres'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ended_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='started_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
