# Generated by Django 3.0.4 on 2020-04-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='addres',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='addres',
            name='vender',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='categori',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Bidder'),
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Item'),
        ),
        migrations.AddField(
            model_name='bidder',
            name='addres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Addres'),
        ),
        migrations.AddField(
            model_name='item',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Auction'),
        ),
        migrations.AddField(
            model_name='vender',
            name='addres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Addres'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Categori',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Category'),
        ),
    ]
