# Generated by Django 3.0.4 on 2020-03-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200331_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
