# Generated by Django 3.0.4 on 2020-04-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200401_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
