# Generated by Django 3.0.4 on 2020-04-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200401_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
