# Generated by Django 2.2.7 on 2020-04-05 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0004_auto_20200404_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='vender',
            name='addres',
        ),
        migrations.AddField(
            model_name='addres',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
