# Generated by Django 3.0.4 on 2020-04-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200406_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='req_deposit',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Auction')),
                ('bidder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Bidder')),
            ],
        ),
    ]
