# Generated by Django 3.0.4 on 2020-03-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_addres_auction_bid_bidder_categori_item_vender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addres',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='addres',
            name='vender',
        ),
        migrations.AddField(
            model_name='bidder',
            name='addres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Addres'),
        ),
        migrations.AddField(
            model_name='vender',
            name='addres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Addres'),
        ),
    ]
