# Generated by Django 3.0.4 on 2020-04-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200406_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Auction'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Bidder'),
        ),
    ]
