# Generated by Django 3.0.4 on 2020-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200331_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categori',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='categori',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
