# Generated by Django 3.0.4 on 2020-04-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200406_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Auction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pyment_type',
            field=models.CharField(choices=[('par_charge', 'par_charge'), ('item_pyment', 'item_pyment')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Item'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Bidder')),
            ],
        ),
    ]
